pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps { git 'https://github.com/bhushan-yadav/full-devops-workflow.git' }
        }
        stage('Build') {
            steps { sh 'docker build -t myapp:latest ./app' }
        }
        stage('Test') {
            steps { sh 'pytest tests/' }
        }
        stage('Deploy') {
            steps {
                ansiblePlaybook credentialsId: 'ansible-ssh-key',
                                inventory: 'ansible/inventory.ini',
                                playbook: 'ansible/site.yml'
            }
        }
    }
}
